"""Simulation state — vectorised arrays of cell quantities.

The state is a thin dataclass of numpy arrays. Mesh structure (neighbours,
border flags) is recomputed each iteration in `mesh.py` from positions, and
is therefore not stored here.

Layout (per the 2010 paper, p. 583, fig. 1):

- A cell is a centre point with concentration values, not a sphere or disc.
  Cells are partitioned into two pools: epithelial cells (which carry Act,
  Inh, Sec, and a differentiation state d_i), and mesenchymal cells
  (which carry only Inh and Sec, and have no reaction terms — eqs. 15, 16
  with degradation+diffusion only).
- Each epithelial cell has one immediately-underlying mesenchymal neighbour
  (paper: "two layers of mesenchymal cells underneath", "each epithelial
  cell has one underlying mesenchymal neighbour"). For Path B's vectorised
  layout we attach mesenchyme as per-cell-column z-layers indexed against
  the same epithelial cell index, rather than maintaining a separate
  mesenchymal cell-list. This is consistent with the FORTRAN's q3d[i, z, s]
  layout but with named fields for clarity.

Initial-condition layout: a hexagonal lattice of `num_active_cells`
epithelial cells generated by the lattice formula
    num_active_cells = 3 * (rad - 1) * rad + 1
(matches `13.f90` allocate_initial_state). For the seal example, rad=4
gives 37 epithelial cells initially.
"""
from __future__ import annotations

from dataclasses import dataclass, field
import math

import numpy as np

from .params import Params


# Number of mesenchymal z-layers underneath each epithelial cell (paper:
# "two layers of mesenchymal cells underneath"). The FORTRAN allocates
# max_z_layers=4 in q3d but uses indices 0=epithelial, 1=upper mesenchyme,
# 2=lower mesenchyme, 3=substrate edge. We expose only the two real
# mesenchymal layers; substrate handling is done as a boundary condition
# in the diffusion step.
N_MESENCHYME_LAYERS: int = 2


@dataclass
class State:
    """Per-cell quantities for the silicoshark simulator.

    Arrays have leading dimension `num_active`, which can grow as cells
    divide. Capacity-grown arrays are not used (numpy arrays can't be
    grown in-place); cell division reallocates with `np.concatenate`.

    Attributes
    ----------
    positions : (N, 3) float64
        x, y, z of each epithelial cell centre. Initial spacing = 1 unit
        (paper: "initial distance between cells equals one unit").
    act, inh, sec : (N,) float64
        Epithelial concentrations of activator, inhibitor, secondary signal.
    diff : (N,) float64
        Differentiation state d_i, clamped to [0, 1] (eq. 6).
    knot : (N,) bool
        True once `act >= 1.0` (paper: "Differentiation is irreversible.
        A cell becomes an enamel knot when [Act] >= 1").
    mes_inh, mes_sec : (N, N_MESENCHYME_LAYERS) float64
        Mesenchymal concentrations attached to each epithelial column.
    rest_length : float
        Constant 1.0 (paper: "p_0 ... is not a parameter of the model.
        Initial distance between cells equals one unit").
    init_anterior, init_posterior, init_lingual, init_buccal : (N,) bool
        Marks the initial-condition border half-planes used to label
        descendants for anterior/posterior bias (eq.-less; Methods, p. 585).
        Daughters inherit one of these flags from their mother on division.
    iter_count : int
        Total elapsed forward-Euler steps.
    """

    positions: np.ndarray
    act: np.ndarray
    inh: np.ndarray
    sec: np.ndarray
    diff: np.ndarray
    knot: np.ndarray
    mes_inh: np.ndarray
    mes_sec: np.ndarray
    init_anterior: np.ndarray
    init_posterior: np.ndarray
    init_lingual: np.ndarray
    init_buccal: np.ndarray
    is_border_topo: np.ndarray | None = None
    """Topological border-cell flags, FORTRAN's first-border-block book-
    keeping. True for the original outer-ring cells; daughters inherit
    True only if BOTH parents are border (per FORTRAN's
    `new_cell_is_external` rule at coreop2d.py:1068). Used by
    `Discretisation.border_definition='topological_descendants'`. Path B
    v2 A6 added this field (wired from the existing `first_border_cell`
    threshold at construction). The geometric `mesh.is_border` is a
    separate, recomputed-each-step quantity.
    """
    rest_length: float = 1.0
    iter_count: int = 0
    first_border_cell: int = 0
    """Threshold index used by the FORTRAN's `first_border_cell` gate.

    Computed at construction time from the initial hex lattice as
    `6 * (rad - 1)` (the count of cells in the outermost ring). Used
    by `Discretisation.knot_threshold_gate='first_border_cell'` (and,
    eventually, by `eq5_apply_to='interior_only'`) to restrict
    knot formation to cells with index `>= first_border_cell`. The
    paper's `'none'` default ignores this field.

    The exact value matches the FORTRAN's `first_border_cell`
    arithmetic per Path B v2 charter §A3.
    """

    @property
    def num_active(self) -> int:
        return self.positions.shape[0]


def hex_lattice(rad: int, fortran_orientation: bool = False) -> np.ndarray:
    """Hexagonal lattice of cells centred at the origin.

    Returns an (N, 2) array of (x, y) coordinates with N = 3*(rad-1)*rad + 1.
    Cell at index 0 is the centre. Spacing = 1 unit.

    Generation strategy: place rings 0..rad-1 around the origin. Ring k
    contains 6*k cells (ring 0 is just the origin).

    Notes
    -----
    `13.f90`'s allocate_initial_state generates a slightly different
    lattice (with an outer "virtual" ring beyond num_active_cells). Path B
    uses the simpler standard hex lattice; the outer ring is a FORTRAN
    book-keeping artefact unnecessary with `scipy.spatial.Delaunay`.

    Orientation
    -----------
    Two orientations are supported, controlled by `fortran_orientation`:

    - `False` (default): rings start at angle 0 (cells at (1,0), (2,0)).
      Conventional axial layout. The v1 simulator and the
      v1-byte-identity baseline depend on this orientation.

    - `True`: rotated 30° clockwise so that cells lie at x=0 on the
      y-axis (e.g., outer ring includes (0, rad), (0, -rad)). This
      matches `13.f90`'s allocate_initial_state output. Required for
      the LEGACY_FORTRAN preset to reproduce the FORTRAN's
      border_bias_x_zero_quirk dynamics on the seal example: the
      FORTRAN's `if x > 0 / elif x < 0` chain in update_cell_position
      excludes cells at exact x=0 from the Bgr z-multiplier, anchoring
      those cells low in z and creating the z gradient that drives
      the FORTRAN's 57-cell plateau. Without cells at exactly x=0,
      the quirk has no targets and the dynamics produce a flat
      border-z curve, mismatching the FORTRAN's seal output by ~50%.
    """
    if rad < 1:
        raise ValueError(f'rad must be >= 1, got {rad}')

    s60 = math.sqrt(3) / 2
    # Six unit-vectors of the hexagonal lattice basis. Picking two:
    e1 = np.array([1.0, 0.0])
    e2 = np.array([0.5, s60])

    pts = [(0.0, 0.0)]
    for ring in range(1, rad):
        # Walk the perimeter of ring `ring` starting at `ring * e1` and
        # stepping along six edges, each `ring` steps long.
        edges = [
            np.array([-0.5,  s60]),  # NW
            np.array([-1.0,  0.0]),  # W
            np.array([-0.5, -s60]),  # SW
            np.array([ 0.5, -s60]),  # SE
            np.array([ 1.0,  0.0]),  # E
            np.array([ 0.5,  s60]),  # NE
        ]
        p = ring * e1
        for edge in edges:
            for _ in range(ring):
                pts.append((float(p[0]), float(p[1])))
                p = p + edge
    arr = np.asarray(pts, dtype=np.float64)
    if fortran_orientation:
        # Rotate 30° (= pi/6) counter-clockwise so the lattice matches
        # FORTRAN's `13.f90` output: corners of ring k at (k*sqrt(3)/2,
        # ±k/2) rather than the conventional axial (k, 0) etc.
        cos30 = math.sqrt(3) / 2
        sin30 = 0.5
        x = arr[:, 0].copy()
        y = arr[:, 1].copy()
        arr[:, 0] = x * cos30 - y * sin30
        arr[:, 1] = x * sin30 + y * cos30
        # Round near-zero coordinates exactly to zero so the FORTRAN
        # `border_bias_x_zero_quirk` (which compares against x=0
        # exactly) fires consistently. Without this, fp noise around
        # the rotated y-axis cells leaves them at x ~ ±1e-16, defeating
        # the strict `if x>0 / elif x<0` chain. FORTRAN's
        # `allocate_initial_state` does the same (line 320:
        # `cls.positions = cls.positions.round(decimals=14)`).
        zero_mask_x = np.abs(arr[:, 0]) < 1e-13
        arr[zero_mask_x, 0] = 0.0
        zero_mask_y = np.abs(arr[:, 1]) < 1e-13
        arr[zero_mask_y, 1] = 0.0
    return arr


def build_initial_state(
    params: Params,
    *,
    lattice_orientation: str = 'axial',
) -> State:
    """Build the initial state for a simulation.

    Initial conditions, per the 2010 paper p. 586:
    - Hexagonal lattice of epithelial cells (`13.f90` uses rad=4 -> 37
      cells; the 2010 paper specifies rad=2 -> 7 cells; both layouts are
      paper-faithful, controlled by the parameter file).
    - Two layers of mesenchyme attached to each epithelial column
      (concentrations zero initially).
    - All concentrations and d_i zero, except Act = init_act on every
      epithelial cell. (FORTRAN initact behaviour; the 2010 paper says
      "an arbitrary constant source of Act in the border epithelial cells
      initially", which we read as compatible with this setup. Future work
      could narrow the seed to border cells only, recorded as a finding.)
    - Initial border half-plane flags: anterior = y > 0, posterior = y < 0,
      lingual = x > 0, buccal = x < 0. (Paper: anterior/posterior border
      cells "have positive y values" / "negative y values"; left/right
      bias is FORTRAN-only via `Lbi`/`Rbi`.)

    `lattice_orientation` selects between the conventional axial layout
    (default) and the FORTRAN-compatible 30°-rotated layout (used by
    LEGACY_FORTRAN to make `border_bias_x_zero_quirk` cells exist).
    See `hex_lattice` for the orientation discussion.
    """
    xy = hex_lattice(params.rad, fortran_orientation=(lattice_orientation == 'fortran'))
    n = xy.shape[0]
    expected = 3 * (params.rad - 1) * params.rad + 1
    if n != expected:
        raise AssertionError(
            f'hex_lattice rad={params.rad} produced {n} cells, '
            f'expected {expected}'
        )

    positions = np.zeros((n, 3), dtype=np.float64)
    positions[:, 0] = xy[:, 0]
    positions[:, 1] = xy[:, 1]
    # Match FORTRAN initial z = 1; the absolute value is arbitrary, but
    # keeping it consistent with the goldens helps cross-validation.
    positions[:, 2] = 1.0

    act = np.full(n, params.init_act, dtype=np.float64)
    inh = np.zeros(n, dtype=np.float64)
    sec = np.zeros(n, dtype=np.float64)
    diff = np.zeros(n, dtype=np.float64)
    knot = np.zeros(n, dtype=bool)

    mes_inh = np.zeros((n, N_MESENCHYME_LAYERS), dtype=np.float64)
    mes_sec = np.zeros((n, N_MESENCHYME_LAYERS), dtype=np.float64)

    init_anterior = positions[:, 1] > 0
    init_posterior = positions[:, 1] < 0
    init_lingual = positions[:, 0] > 0
    init_buccal = positions[:, 0] < 0

    # `first_border_cell` is the threshold index used by Discretisation
    # gates that the FORTRAN spells `i >= first_border_cell` (interior
    # cells in the FORTRAN's reversed lattice, where indices [0,
    # first_border_cell-1] are the outer ring and the centre is the
    # last index). silicoshark uses the inverted convention (centre at
    # index 0, outer ring at high indices), so the threshold is the
    # COUNT OF INTERIOR CELLS, and the corresponding gate in the
    # silicoshark numbering is `idx < first_border_cell` for interior
    # and `idx >= first_border_cell` for border.
    #
    # For rad=R the count of interior cells (centre + rings 1..R-2) is
    #   1 + 6 + 12 + ... + 6*(R-2) = 1 + 6 * (R-2)*(R-1)/2
    #                               = 1 + 3 * (R-1) * (R-2).
    # rad=1 -> 1 (single centre, no border); the gate is inert (all
    # cells qualify as interior). rad=2 -> 1, rad=3 -> 7, rad=4 -> 19.
    #
    # This is a Path B v2 A6 fix: the v1/A5 implementation used
    # FORTRAN's `6 * (rad - 1)` directly, which matches FORTRAN's
    # value but means the wrong cells under silicoshark's lattice
    # convention. See docs/findings/2026-05-05-... and `Discretisation`
    # field docstrings for `eq5_apply_to` / `knot_threshold_gate`.
    rad = params.rad
    first_border_cell = 1 + 3 * (rad - 1) * (rad - 2) if rad >= 2 else 1

    # Topological border flags: cells with index >= first_border_cell
    # form the outer ring. Daughters of two-border parents inherit True;
    # daughters with at least one interior parent are interior. See
    # State.is_border_topo and `divide_cells` for the inheritance rule.
    is_border_topo = np.arange(n) >= first_border_cell

    return State(
        positions=positions,
        act=act,
        inh=inh,
        sec=sec,
        diff=diff,
        knot=knot,
        mes_inh=mes_inh,
        mes_sec=mes_sec,
        init_anterior=init_anterior,
        init_posterior=init_posterior,
        init_lingual=init_lingual,
        init_buccal=init_buccal,
        is_border_topo=is_border_topo,
        first_border_cell=first_border_cell,
    )
